/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { MyToken } from "./MyToken";
export type { SaveERC20 } from "./SaveERC20";
